### ISSUE TITLE
Added How Many <select /> to AppLobby; Needs Styling

### ISSUE THREAD

**Issue by pjz987** [Solaros711/pixelparty#18]
Hey Billy.
I'm just playing with this to see how github issues work, but if you want you can check it out and fix it because it shouldn't be too hard.
I added a How Many? `<select/>` so a host can choose a game size of 2-4 players.  It works fine but it doesn't jive with the styling.  Feel free to fix it as you see fit.
Regards,
--Pete

**Comment by barnetb** [comment]
In progress...I'll make the fix on the 'design' branch and then submit a pull request once completed.

**Comment by barnetb** [comment]
Forgot that were working off of 'dev-branch-2' now...so actually it'll be via a new branch named 'design-2'.

**Comment by pjz987** [comment]
All good, I think the idea is to delete a branch once it's merged into another... then you good just make a branch with the same name again... but were doing things extra confusing so....

**Comment by barnetb** [comment]
Agreed.  Guess that should be the responsibility of the person doing the merge?

**Comment by barnetb** [comment]
Done.  Just made pull request to dev-branch-2 from design-2.

**Comment by pjz987** [comment]
finally closed :1st_place_medal:
