### ISSUE TITLE
Review art-on-landing-page

### ISSUE THREAD

**Issue by pjz987** [Solaros711/pixelparty#38]
Hey Billy,
I made a branch that showcases random art in `AppLobby.js`.  It works, but it doesn't look great. For immediate styling purposes there's a  new `games-and-showcase` div that contains `wait-host-container` and the showcase div w/ the canvas.  We could merge it into `dev-branch-2`... but it might be better to wait on that until we've made more changes to the landing page.  In any case, you can just `checkout` the new branch locally to get a general idea of how I want the showcase to look.
Thanks,
--Pete

**Comment by barnetb** [comment]
Sounds good.  I'll make changes to landing page and demo to you in first half of class today before integrating the showcase.
